# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Stop with `docker stack rm grid`

version: '3.7'

services:
  hub:
    image: selenium/hub:3.141.59-iron
    volumes:
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-iron
    volumes:
      - /dev/shm:/dev/shm
      - /etc/timezone:/etc/timezone:ro
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
      replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox:3.141.59-iron
    volumes:
      - /dev/shm:/dev/shm
      - /etc/timezone:/etc/timezone:ro
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
      replicas: 1
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  chrome-debug:
    image: thiswind/selenium-chrome-debug:latest 
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
      - /etc/timezone:/etc/timezone:ro
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
      replicas: 1
      placement:
          constraints: [node.role == manager ]
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

